import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-nuestro',
  templateUrl: './nuestro.component.html',
  styleUrls: ['./nuestro.component.scss']
})
export class NuestroComponent implements OnInit {
  popup= false;
  titulo = '';
  form_lista:any;
  public lista:any =
    {
      'MAPP': [
        'Rosa María Matus Colina',
        'Nidia Maribel 	Mayoral Peña',
        'Norma Gabriela 	Medina Galindo',
        'Julio José 	Mejía Fontalvo',
        'Judith 	Miraflores Ruíz',
        'Felipe Eduardo 	Molina Perezchica',
        'Ulises Eduardo 	Montalvo Valverde',
        'Rosa María 	Montes de Oca Huerta',
        'Bogart Cristóbal	Montiel Reyna',
        'Carmen Cecilia 	Morales López',
        'Jesús Alberto 	Moreno López',
        'Oscar 	Muciño Bastida',
        'Jorge José	Nader Nemer',
        'Carlos Alberto 	Nava Hernández',
        'Diana Andrea 	Nava Ugalde',
        'Oscar 	Noh Cocom',
        'Uriel 	Ochoa Chávez',
        'Marco Antonio 	Orbe Ruíz',
        'Roberto 	Orenda Robles',
        'Juan Cristóbal 	Orozco Alonso',
        'Luis Rey 	Ortega Medina',
        'Mónica Carmen	Palma Rivera',
        'Anaid Bernice	Pedroza Mejía',
        'Fabiola 	Pérez Soriano',
        'Carol Denisse 	Pérez Toledo',
        'Karina 	Pérez Velázquez',
        'Sergio 	Piñeiro Camacho',
        'Daher Antonio 	Puch Rivera',
        'Viridiana 	Quezada Pérez',
        'Antonio Eremiev 	Quiroz Acosta',
        'Veronica Sofia 	Ramírez Hernández',
        'Ernesto Hermilo 	Rangel Rodriguez',
        'Braulio 	Reyes Sosa',
        'Julio César 	Ríos Roa',
        'Joel Humberto 	Rodríguez López',
        'Roxana 	Rodríguez Navarrete',
        'José Javier 	Rodríguez Socorro',
        'María del Carmen 	Rojas Domínguez',
        'Alejandra 	Roldán Hernández',
        'José Luis 	Salazar Tola',
        'Gabriela Josefina 	Saldaña Luna',
        'Hilda Andrea	Saldívar Trujillo',
        'Estephani 	Salinas Alanis',
        'Rosa Adela 	Sánchez Alarcón',
        'Raul Ricardo 	Sánchez Álvarez',
        'Rita 	Sánchez Jiménez',
        'Rafael 	Sánchez Ramos',
        'Manuel 	Sánchez Ruíz',
        'Itzel 	Sánchez Torres',
        'Oscar 	Sarmiento Sarmiento',
        'Jessica 	Sierra García',
        'María Luisa 	Solís Juárez',
        'Juan Fernando 	Soto Chávez',
        'Abelardo 	Stringel Laguna',
        'Sofonías Benito	Suárez Zorrilla',
        'Juan Manuel 	Torres Paredes',
        'Claudia Ived 	Torres Soria',
        'Devi Saranyu 	Ugalde Jiménez',
        'Teresa Yazmin 	Valdés Chávez',
        'Delyana de Jesús 	Vargas Loaiza',
        'Salec 	Velázquez Nande',
        'Arantxa Jarumi 	Villeda Castillo',
        'José Luis 	Zárate Pérez',
        'Juan Carlos 	Zárate Pérez',
        'Yessica 	Zuñiga Padrón',
        'José Arturo 	Carbajal Chee',
        'Federico 	Castrejón Hampshire',
        'Yanela 	Cortés González',
        'Alejandro 	Cuevas Álvarez',
        'Ramón 	de La Cruz Sánchez',
        'Carlos Armando 	de los Santos García',
        'Luis Ramiro 	Echeverría Hernández',
        'Alejandro A.VII 	Gallardo López',
        'Luis Ángel 	López Vargas'

      ],
      'MEPP':[
        'Edith Griselda 	Amaya Mayagoitia',
        'Luis Gerardo 	Andrade Macías',
        'Blas Alonso 	Barbosa López',
        'Hugo 	Bárcenas López',
        'Enrique Joel 	Burton Mendoza',
        'David Jorge 	Cruz Córdova',
        'Gloria María 	De Alejandro Calvo',
        'Mónica Gabriela 	De La Luz Eslava',
        'Oziel Armando 	De Lara Martínez',
        'Casandra 	Gayosso Montes de Oca',
        'Esmeralda 	González Nájera',
        'Luis 	Guevara Paredes',
        'María Luisa 	Guzmán Vázquez',
        'Eli Benjamín 	Hernández Rodríguez',
        'Martha Gabriela 	Izaguirre Granados',
        'Juan Manuel 	López Arroyo',
        'Gerardo 	López Mendoza',
        'Ismael 	López Soto',
        'Mariana 	Martínez García',
        'Lorena Margarita 	Martínez Medina',
        'Marco Fernando 	Mier Velasco',
        'Carlos Armando 	Navarrete Maldonado',
        'Cecilia Nohemi 	Oliva Juárez',
        'Karla Jannette 	Ortiz Gómez',
        'Diego 	Palmero Muñiz',
        'José Gil 	Peyro Medina',
        'Ivette Amairani 	Puc Tuz',
        'Viviana 	Rangel Flores',
        'Blanca Emilia 	Reyes Ibarra',
        'Elba 	Rojas Pérez',
        'Hansell Jesús 	Sabido Ocampo',
        'José Antonio 	Salinas Bolaños',
        'Diana Citlalli 	Tapia Martínez',
        'Kevin Sander 	Tiburcio Zamudio',
        'Alejandro 	Vallejo Cortés',
        'Alberto 	Vélez Valdés',
        'Virginia Guadalupe 	Villanueva Quijano',
        'Raúl Alejandro 	Zavala Miranda',
        'Elisa Johanna 	Zúñiga Arellano'

      ],
      'MFPP':[
        'Diana Berenice 	Acevedo Soto',
        'Gustavo 	Álvarez Larios',
        'Alfredo Javier 	Arias Casas',
        'Karina 	Barrios Velázquez',
        'Angel Servando 	Canto Ake',
        'Luis Roberto 	Castillo Sollano',
        'Dario 	Coyotzi Nava',
        'Nicanor 	Díaz Escamilla',
        'Sergio 	Escalante Jiménez',
        'Juan Manuel 	Flores Medina',
        'Yahairy Concepción 	García Cohuo',
        'Gonzalo 	García Cruz',
        'Ilse 	Garrido Cervera',
        'Ulises 	González Garduño',
        'Jazmín Lucero 	González Martínez',
        'Esteban 	Jiménez Pérez',
        'Irving Uriel 	Mendoza Estrello',
        'Isabel 	Muñoz García',
        'José Enmanuel 	Orozco Aispuro',
        'Michael 	Ponce Ríos',
        'Camilo Graciano 	Ramírez Landetta',
        'Nara Cyntia 	Ríos Velázquez',
        'Ricardo Román 	Sánchez Hau',
        'Luis Francisco 	Santiago Hernández',
        'Edwin Adolfo 	Tun Cetina',
        'Jesús Alberto 	Uresti Amaya',
        'Mario 	Vázquez Cantú',
        'Pedro Luis 	Vázquez Lobato',
        'Daniel 	Villarruel Palma'

      ],
      'MSPPP':[
        'Miguel Angel 	Abundio Del Angel',
        'Gloria 	Aguilar Rodríguez',
        'Leobardo Miguel 	Aguilar Rosales',
        'Juan Raúl 	Alcocer Cruz',
        'Jesús Daniel 	Alvarado Preciado',
        'Ana Gabriela 	Amor Gilbon',
        'Raymundo 	Aquino Hernández',
        'Omar 	Arriola García',
        'José Armando 	Asiain Morales',
        'Francisco 	Avila Torres',
        'Abraham Martín 	Ayala López',
        'Osvaldo Isaac 	Balderas García',
        'María de los Angeles Marisol	Baleón Reyes',
        'Margarita 	Barragán Alejandro',
        'Antonio Humberto 	Barrios Bolado',
        'Álvaro de Jesús 	Bojórquez Espinosa',
        'Shareny Vanessa 	Bustamante Sánchez',
        'Luis Fernando 	Carrillo Pérez',
        'Rodrigo 	Cerda Cornejo',
        'Luis Manuel 	Chagollán Pelayo',
        'Raúl 	Chávez Chapina',
        'Daniel 	Chávez Garcia',
        'Víctor Manuel 	Colorado Olan',
        'Dayanne 	Cruz Hernández',
        'David Antonio 	Dávila Monroy',
        'Sonia 	De Jesús Garay',
        'María Guadalupe 	Díaz Estrada',
        'Salvador 	Ensuastegui Rocillo',
        'Vicente 	Escobar Caballero',
        'Oscar Rafael 	Esparza Chagolla',
        'Felipe 	Estrada Muñoz',
        'Horacio Magdiel 	Estrada Soto',
        'Ileana Fabiola 	Filio Rivera',
        'Alfonso 	Flores Rojas',
        'Jesús Alberto 	Flores Vizcarra',
        'Mayra Alejandra 	Fraire Camarena',
        'Porfirio 	Gámez Medina',
        'Yhon Flabio 	García Arbeláez',
        'Manuel Miranda 	García Calderón',
        'Arturo 	García Gallardo',
        'Margarito 	García García',
        'Marlene del Carmen 	García García',
        'Javier 	García García',
        'Carlos Martín 	García Oviedo',
        'Gregorio Neftali 	García Pérez',
        'Heriberto 	García Romero',
        'Víctor Hugo 	Garzón Barrientos',
        'Francisco José 	Gómez Guerrero',
        'María de Lourdes 	González Reyes',
        'Engelbert 	Granados Saynes',
        'Eduardo 	Griss Kauffman',
        'Judith 	Gutiérrez Narváez',
        'Andrés 	Gutiérrez Sánchez',
        'Pedro 	Hernández Méndez',
        'Carlos 	Herrera Pinales',
        'José Francisco 	Jiménez Vargas',
        'Rabindranath 	Juárez Mayorquin',
        'Héctor Alonso 	Lechuga Pineda',
        'David 	López Anguiano',
        'José Antonio 	López Chan',
        'Carlos Alberto 	López Figueroa',
        'Edgar Omar 	López Flores',
        'Tania Itzel 	López García',
        'Hirum	Luciano Pérez',
        'Omar 	Luevano Torres',
        'Diego Orlando 	Luna Jaime',
        'Arturo Iván 	Luna Martínez',
        'Araceli 	Luna Mendoza',
        'Marco Antonio 	Mariño Leal',
        'Julio César 	Marta Sánchez',
        'Jorge 	Martínez Espinoza',
        'Cynthia Yesenia 	Martínez Martínez',
        'Karina del Rubí 	Martínez Reyes',
        'Manuel 	Matamoros Sánchez',
        'J. Inés 	Meléndez Estrada',
        'Rogelio Fernando 	Melo Ramírez',
        'Francisco Alejandro 	Méndez Valadez',
        'Jorge Luis 	Mendoza Escalante',
        'Hermelindo 	Mendoza Merino',
        'Yesenia 	Mendoza Pérez',
        'Rogelio 	Mendoza Ramirez',
        'Mónica Leticia 	Mendoza Torres',
        'Javier 	Mercado Uribe',
        'Lucia Virginia 	Meza Guzmán',
        'Mauricio Yovani 	Molina Medinilla',
        'Miguel Ángel 	Montero Palomo',
        'Rosendo 	Montiel Morales',
        'María Eugenia 	Morales Rivera',
        'Ana Cristina 	Morales Villar',
        'Raymundo 	Moreno Barrera',
        'Adrián 	Muñoz Navarro',
        'Irma Liliana 	Murillo Domínguez',
        'Juan Jesús 	Murillo Santos',
        'Diana Isabel 	Nuño Acevedo',
        'Pedro Nolberto 	Olivera Silva',
        'Jorge 	Orizaga Castañeda',
        'Marcus Vinicius 	Ornelas Quesada',
        'José Enmanuel 	Orozco Aispuro',
        'Jennifer Vianey 	Ortiz Rodríguez',
        'César Antonio 	Perales Esparza',
        'Tania Carolina 	Peralta Carreón',
        'Francisco 	Pérez Conde',
        'Javier Israel 	Pérez Gómez',
        'Sonia Fernanda 	Pérez Leal',
        'Laura Angélica 	Pérez Rodríguez',
        'Irving 	Prieto Lorenzo',
        'Jesús Alberto 	Ramírez Manzur',
        'Roberto 	Ramírez Mendoza',
        'Alfredo 	Ramírez Saldaña',
        'Manuel Ismael 	Ramos Portillo',
        'Jarintzin 	Resendiz Camacho',
        'Aurora 	Reyna Guadarrama',
        'Vasshio 	Reza Aranda',
        'Arely 	Rivera Bravo',
        'José Antonio 	Rodríguez de Caso',
        'René Gerardo 	Rodríguez Dorado',
        'Silvestre 	Rodríguez Marín',
        'Juan Manuel 	Rojas Díaz',
        'Guillermo 	Romero Robles',
        'Ana Belén 	Rúa Lugo',
        'Héctor Vélez 	Ruiz Gaitán',
        'David 	Salamanca Ortiz',
        'Tiver Olaff 	Salas Leyva',
        'Micaela 	Salcedo Álvarez',
        'Raúl Ernesto 	Salcedo Rosales',
        'María Teresa 	Salinas Salazar',
        'Lourdes Carolina 	Samaniego Zozaya',
        'Noel Alfredo 	Sánchez Benítez',
        'Andrés 	Sánchez Mayo',
        'Luis 	Sánchez Pérez',
        'Débora del Rosario 	Sánchez Torres',
        'José Alfonso 	Sánchez Valberde',
        'Lluvanitzy 	Santaella Molina',
        'Nelly Guadalupe 	Santoyo Muñoz',
        'Alfredo Zarel 	Saucedo Sánchez',
        'Miguel Ángel 	Solano Mora',
        'José Daniel 	Solis Morales',
        'Juan Pablo 	Sosa Ramos',
        'Mariana Inés 	Soto Sánchez',
        'Juan Enrique 	Téllez Barrón',
        'Francisco Antonio 	Tinoco Castañeda',
        'María Eugenia 	Torres Pérez Tejada',
        'José 	Trigos Lili',
        'Jesús Dolores 	Valle Herrera',
        'Román Enrique 	Vargas Pérez',
        'Carlos 	Vásquez Rios',
        'Amador 	Velasco Cisneros',
        'Jaime 	Velazco Velazco',
        'Héctor Enrique 	Verdugo Ramírez',
        'Francisco Enrique 	Vilchis Villagran',
        'Herminia Josefina	Villa Luna',
        'Estefany 	Zacatzi Cortés',
        'Joel 	Zagal Ortíz',
        'Alberto 	Zamora Ramírez',
        'Jonathan Enrique 	Zuñiga Islas'

      ],
      'MBP':[
        'José Arturo 	Carbajal Chee',
        'Federico 	Castrejón Hampshire',
        'Yanela 	Cortés González',
        'Alejandro 	Cuevas Álvarez',
        'Ramón 	de La Cruz Sánchez',
        'Carlos Armando 	de los Santos García',
        'Luis Ramiro 	Echeverría Hernández',
        'Alejandro A. VII 	Gallardo López',
        'Luis Ángel 	López Vargas',
        'Roberto Álvaro 	Núñez Jaramillo',
        'Alma Guadalupe 	Ocampo Vázquez',
        'Irais Fabiola 	Otero Rocha',
        'Marco Antonio 	Quiroz Carbajal',
        'Alejandro 	Robledo Muro',
        'Anacely 	Santiago Ayuso',
        'Ana Laura 	Soto Romero',
        'Ana Karen 	Torres Ata',
        'Cynthia Daniela 	Tovar Vázquez',
        'Juliana Maritza 	Zamora García',
        'Lucero Adriana 	Zamora García',
        'Ana Luisa Ivonne 	Zamora García'

      ]
    }

  constructor() { }

  ngOnInit(): void {
  }
  openpop(categotia:string){
    console.log(this.lista);
    this.form_lista = this.lista[categotia];
    switch (categotia) {
      case 'MAPP':
        this.titulo = 'Maestría en Administración y Políticas Públicas';
        break;
      case 'MEPP':
        this.titulo = 'Maestría en Evaluación de Políticas Públicas'
        break;
      case 'MFPP':
        this.titulo = 'Maestría en Finanzas Públicas'
        break;
      case 'MSPPP':
        this.titulo = 'Maestría en Seguridad Pública y Políticas Públicas'
        break;
      case 'MBP':
        this.titulo = 'Maestría en Administración de Negocios'
        break;
    }
    this.popup=true;
  }
}
